# Generated by Django 3.1 on 2020-08-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectchoice',
            name='name',
        ),
    ]
